---
title: "GitHub_collaboration"
author: "MSCI 599"
output: html_document
---

HOW DO I START COLLABORATING?
So far, we've been the sole "author" on some repo/project we're working in. Often, we'll want to be collaborating on a paper or data analysis work. If that's the case, we'll want to add a collaborator.
**IMPORTANT: Collaborators will be able to push/pull changes directly to/from the repo you share with them, so make sure it's someone you want to allow!**
OK, once you have confirmed that you want to add someone as a collaborator:
• Figure out what name or username or email they have associated with their github account
• While in the github repo that you want to add them to as a collaborator, click on 'Settings'
(under 'Watch')
• Click 'Collaborators'
• Enter their name(s) (any of the above to search)
• When you find the right one, click 'Add Collaborator'
• And now they can clone and push/pull directly, and you can both be working on the same
project
A Practice Task: Creating a repo/project, and adding a collaborator who can work on it with you.
Primary user:
• In github, create a new repo called 'test-yourname' (like 'test-allison' is mine...)
• Drop the "sleep.csv" file into the repo
• Click on 'Clone or Download' to copy the repo URL
• Go to RStudio, create a new Project with version control, linked to the repo you just created
using the URL (as described above)
• In RStudio, open a new markdown document
• Write code to prepare a basic scatterplot graph of animal gestation time v. lifespan
• Save the markdown document (and knitted doc, if you want...)
• Stage, commit, and push the files to github (and ensure they show up in the Repo)
• Add your neighbor as a collaborator in the repo
Collaborator:
• Clone/download the repo (same name) that you're now collaborating on
• Update something obvious about the graph (e.g. point color)
• Commit and push your changes back to github
• Check out what happens in the repo you're sharing

### Acknowledgements

From Allison Horst's GitHub tutorial:
https://github.com/allisonhorst/esm-206-2018/tree/master/week_6